
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Users/joegf/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/mnt/c/Users/joegf/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.15.6-hotspot/bin/"
      - "/mnt/c/Program Files (x86)/VMware/VMware Workstation/bin/"
      - "/mnt/c/Python312/Scripts/"
      - "/mnt/c/Python312/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files/WireGuard/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files/PuTTY/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/metasploit-framework/bin/"
      - "/mnt/c/Program Files/Tailscale/"
      - "/mnt/c/Program Files/Sunshine/"
      - "/mnt/c/Program Files/Sunshine/tools/"
      - "/mnt/c/Program Files/Docker/Docker/resources/bin/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Users/joegf/.cargo/bin/"
      - "/mnt/c/Users/joegf/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/joegf/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Program Files (x86)/Nmap/"
      - "/mnt/c/msys64/ucrt64/bin/"
      - "/mnt/c/Users/joegf/AppData/Local/Microsoft/WinGet/Links/"
      - "/mnt/c/Users/joegf/.vscode/extensions/vscjava.vscode-java-debug-0.59.0/bundled/scripts/noConfigScripts/"
      - "/snap/bin/"
    searched_directories:
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Users/joegf/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/mnt/c/Users/joegf/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.15.6-hotspot/bin"
        - "/mnt/c/Program Files (x86)/VMware/VMware Workstation/bin/"
        - "/mnt/c/Python312/Scripts/"
        - "/mnt/c/Python312/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files/WireGuard/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/metasploit-framework/bin/"
        - "/mnt/c/Program Files/Tailscale/"
        - "/mnt/c/Program Files/Sunshine"
        - "/mnt/c/Program Files/Sunshine/tools"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Users/joegf/.cargo/bin"
        - "/mnt/c/Users/joegf/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/joegf/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Program Files (x86)/Nmap"
        - "/mnt/c/metasploit-framework/bin"
        - "/mnt/c/msys64/ucrt64/bin"
        - "/mnt/c/Users/joegf/AppData/Local/Microsoft/WinGet/Links"
        - "/mnt/c/Users/joegf/.vscode/extensions/vscjava.vscode-java-debug-0.59.0/bundled/scripts/noConfigScripts"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.114.1-microsoft-standard-WSL2 - x86_64
...
